sudo: false

language: node_js

os:
  - osx
  - linux

node_js:
  - "8"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - clang-3.3
      - libx11-dev
      - libxkbfile-dev

script: 'npm test'

git:
  depth: 2
